# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osi_sensordata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'osi_sensordata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14osi_sensordata.proto\x12\x04osi3\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\r\"\x1b\n\nIdentifier\x12\r\n\x05value\x18\x01 \x01(\x04\"C\n\x0bSpherical3d\x12\x10\n\x08\x64istance\x18\x01 \x01(\x01\x12\x0f\n\x07\x61zimuth\x18\x02 \x01(\x01\x12\x11\n\televation\x18\x03 \x01(\x01\"[\n\x0eRadarDetection\x12#\n\x08position\x18\x03 \x01(\x0b\x32\x11.osi3.Spherical3d\x12\x17\n\x0fradial_velocity\x18\x05 \x01(\x01\x12\x0b\n\x03rcs\x18\x07 \x01(\x01\"=\n\x12RadarDetectionData\x12\'\n\tdetection\x18\x02 \x03(\x0b\x32\x14.osi3.RadarDetection\"=\n\x0b\x46\x65\x61tureData\x12.\n\x0cradar_sensor\x18\x02 \x03(\x0b\x32\x18.osi3.RadarDetectionData\"~\n\nSensorData\x12\"\n\ttimestamp\x18\x02 \x01(\x0b\x32\x0f.osi3.Timestamp\x12#\n\tsensor_id\x18\x05 \x01(\x0b\x32\x10.osi3.Identifier\x12\'\n\x0c\x66\x65\x61ture_data\x18\x1a \x01(\x0b\x32\x11.osi3.FeatureDataB\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osi_sensordata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_TIMESTAMP']._serialized_start=30
  _globals['_TIMESTAMP']._serialized_end=73
  _globals['_IDENTIFIER']._serialized_start=75
  _globals['_IDENTIFIER']._serialized_end=102
  _globals['_SPHERICAL3D']._serialized_start=104
  _globals['_SPHERICAL3D']._serialized_end=171
  _globals['_RADARDETECTION']._serialized_start=173
  _globals['_RADARDETECTION']._serialized_end=264
  _globals['_RADARDETECTIONDATA']._serialized_start=266
  _globals['_RADARDETECTIONDATA']._serialized_end=327
  _globals['_FEATUREDATA']._serialized_start=329
  _globals['_FEATUREDATA']._serialized_end=390
  _globals['_SENSORDATA']._serialized_start=392
  _globals['_SENSORDATA']._serialized_end=518
# @@protoc_insertion_point(module_scope)
